### ISSUE TITLE
severe: It keeps tracking

### ISSUE THREAD

**Issue by NitkarshChourasia** [Vidhi-bhutia/Volume-Control-Through-Hands#2]
We use webcam.
Our hands get tracked constantly.
When I increase the volume it works as expected.
But when I stop increasing the volume, it at an accelerated speed decreases the volume.
I have to hide my whole hand for it to let the volume stay the same.

The program isn't complete.
Let's improve the program further.

**Comment by Vidhi-bhutia** [comment]
Hii Nikarsh, You are right 
I am working on further improvements in the project.
You can connect me through linkedin to discuss further and we can work together

**Comment by NitkarshChourasia** [comment]
Okay.
